/*
 This source file is part of the SE-0529 reference implementation

 Copyright (c) 2020 - 2026 Apple Inc. and the Swift System project authors
 Licensed under Apache License v2.0 with Runtime Library Exception

 See https://swift.org/LICENSE.txt for license information
*/

import Testing
@testable import FilePath

// ===========================================================================
// PROBE TESTS — parser-correctness probes of the normalization core
// (FilePath.swift / Windows.swift / Darwin.swift / Parsing.swift).
//
// These are CHARACTERIZATION tests added by a normalization-core probe. Each
// pins the *currently observed* decomposition of a degenerate / edge input so
// that any future change to the parser surfaces here. They were generated by
// observing `filepath-play` output and recording the actual result.
//
// Per-probe notes mark whether the SE-0529 proposal SPECIFIES the result or is
// SILENT. Where the proposal is SILENT, the assertion pins observed behavior
// only — it is NOT a claim that the value is the proposal-mandated one. Those
// silent cases are reported as gaps in the accompanying findings writeup; they
// were NOT "decided" here.
//
// All inputs here are confirmed ABSENT from PathTestCases.swift (no existing
// rows are duplicated or modified). Inputs that already have rows there
// (e.g. `/.vol/1234/5678`, `/.vol/1234/2`, `/.nofollow`, `/.resolve/0`,
// `\\.\`, `\\?\`) are referenced in comments but not re-asserted.
//
// Nested in AllTests.DecompositionTests so these run inside the single
// `@Suite(.serialized)` umbrella (REVIEW_ONLY_platform is not thread-safe).
// Assertions and platform selection go through the TestSupport seam.
// ===========================================================================

extension AllTests.DecompositionTests {

  /// Assert the four primary decomposition fields for `input` on `platform`.
  /// The default `#_sourceLocation` captures the *caller's* location, so a
  /// failure points at the probe row rather than this helper.
  private func probe(
    _ input: String,
    platform: REVIEW_ONLY_Platform,
    anchor: String?,
    components: [String],
    trailingSeparator: Bool = false,
    printed: String,
    sourceLocation: SourceLocation = #_sourceLocation
  ) {
    withPlatform(platform) {
      guard let path = FilePath(input) else {
        expectNotNil(Optional<Int>.none,
          "[\(platform)] \(input.debugDescription) FilePath init returned nil",
          sourceLocation: sourceLocation)
        return
      }
      expectEqual(path.anchor?.description, anchor,
        "[\(platform)] \(input.debugDescription) anchor: got \(path.anchor?.description.debugDescription ?? "nil")",
        sourceLocation: sourceLocation)
      expectEqual(path.components.map(\.description), components,
        "[\(platform)] \(input.debugDescription) components: got \(path.components.map(\.description))",
        sourceLocation: sourceLocation)
      expectEqual(path.hasTrailingSeparator, trailingSeparator,
        "[\(platform)] \(input.debugDescription) trailingSeparator: got \(path.hasTrailingSeparator)",
        sourceLocation: sourceLocation)
      expectEqual(path.description, printed,
        "[\(platform)] \(input.debugDescription) printed: got \(path.description.debugDescription)",
        sourceLocation: sourceLocation)
    }
  }

  // MARK: - Probe 1: Darwin relative-portion re-parse
  //
  // `_normalizeDarwin` extracts the relative portion into a fresh string and
  // dot-normalizes it; that path re-runs `_parseRoot()` on the slice. This
  // pins that a relative component literally NAMED like an anchor token
  // (`.vol`, `.nofollow`, `.resolve`) does NOT spuriously produce a second
  // anchor: the leading anchor stands and the token-named bytes remain plain
  // components.
  //
  // SPECIFIED: the proposal's general model — anchor is the leading
  // volfs/resolve anchor, everything after is opaque components (lines 91,
  // 103, 105 of the proposal). No conflict observed.
  @Test
  func probeDarwinRelativeReparse() {
    // .vol token as a relative component under a volfs anchor.
    probe("/.vol/1234/5678/.vol/x", platform: .darwin,
      anchor: "/.vol/1234/5678", components: [".vol", "x"],
      printed: "/.vol/1234/5678/.vol/x")
    // .nofollow token as a relative component under a volfs anchor.
    probe("/.vol/1234/5678/.nofollow/x", platform: .darwin,
      anchor: "/.vol/1234/5678", components: [".nofollow", "x"],
      printed: "/.vol/1234/5678/.nofollow/x")
    // .resolve/3 tokens as relative components under a volfs anchor.
    probe("/.vol/1234/5678/.resolve/3/x", platform: .darwin,
      anchor: "/.vol/1234/5678", components: [".resolve", "3", "x"],
      printed: "/.vol/1234/5678/.resolve/3/x")
    // .vol tokens as relative components under a .nofollow anchor.
    probe("/.nofollow/.vol/1234/5678", platform: .darwin,
      anchor: "/.nofollow/", components: [".vol", "1234", "5678"],
      printed: "/.nofollow/.vol/1234/5678")
    // .nofollow token as a relative component under a .nofollow anchor.
    probe("/.nofollow/.nofollow/x", platform: .darwin,
      anchor: "/.nofollow/", components: [".nofollow", "x"],
      printed: "/.nofollow/.nofollow/x")
    // Inner `.resolve/1` is NOT canonicalized: canonicalization is anchor-only,
    // and here `.resolve/1` is in component position under a `.resolve/3/`
    // anchor.
    probe("/.resolve/3/.resolve/1/x", platform: .darwin,
      anchor: "/.resolve/3/", components: [".resolve", "1", "x"],
      printed: "/.resolve/3/.resolve/1/x")
  }

  // MARK: - Probe 2: bare resolve/vol anchors without trailing content
  //
  // FINDING / GAP: the proposal only ever shows resolve/nofollow anchors in
  // SLASH-TERMINATED form (`/.nofollow/`, `/.resolve/3/`) and only shows the
  // canonicalization rules with a trailing slash (`/.resolve/1/` ->
  // `/.nofollow/`, proposal line 220; `/.vol/NNNN/2/` -> `/.vol/NNNN/@/`,
  // line 221). It does NOT specify the BARE no-trailing-slash forms.
  //
  // Observed asymmetry (proposal SILENT on it; principled per XNU — a volfs
  // anchor is a complete inode reference, while resolve/nofollow are prefixes
  // that modify a FOLLOWING path):
  //   * `_parseVol` recognizes `/.vol/F/I` WITHOUT a trailing slash; the
  //     `2`->`@` canonicalization also fires without one.
  //   * `_parseResolve`/`_parseNofollow` REQUIRE the trailing slash; bare
  //     `/.resolve/N` and `/.nofollow` fall through to a plain `/` root with
  //     the bytes as regular components, and `_canonicalizeDarwinAnchor` does
  //     NOT fire on `/.resolve/1` (it matches the literal `/.resolve/1/`).
  //
  // Already pinned elsewhere (NOT re-asserted): `/.nofollow`, `/.resolve/0`,
  // `/.vol/1234/5678`, `/.vol/1234/2` have rows in PathTestCases.swift.
  @Test
  func probeBareResolveVolAnchors() {
    // GAP: bare `/.resolve/1` — flag 1 is the canonicalizing flag, but with no
    // trailing slash it is NOT a resolve anchor and does NOT canonicalize.
    probe("/.resolve/1", platform: .darwin,
      anchor: "/", components: [".resolve", "1"],
      printed: "/.resolve/1")
    // SPECIFIED (proposal line 220): `/.resolve/1/` canonicalizes to
    // `/.nofollow/`. Here with NO following path -> anchor only, no components.
    probe("/.resolve/1/", platform: .darwin,
      anchor: "/.nofollow/", components: [],
      printed: "/.nofollow/")
    // GAP: bare `/.resolve/3` (non-canonicalizing flag) — same fall-through.
    probe("/.resolve/3", platform: .darwin,
      anchor: "/", components: [".resolve", "3"],
      printed: "/.resolve/3")
    // GAP-adjacent: `/.vol/1234/2/` — the `2`->`@` canonicalization fires, and
    // the trailing slash is a trailing separator (the volfs anchor is not
    // slash-terminated). Proposal line 221 shows this rule with a trailing
    // slash; line 550/573 confirm the volfs trailing slash is a separator.
    probe("/.vol/1234/2/", platform: .darwin,
      anchor: "/.vol/1234/@", components: [], trailingSeparator: true,
      printed: "/.vol/1234/@/")
    // Linux contrast for the same bytes: no Darwin anchor magic at all.
    probe("/.resolve/1", platform: .linux,
      anchor: "/", components: [".resolve", "1"],
      printed: "/.resolve/1")
  }

  // MARK: - Probe 3: Windows three-or-more leading backslashes
  //
  // FINDING / GAP: `_prenormalizeWindowsRoots` returns after the FIRST
  // backslash for 3+ leading backslashes ("NOT a UNC/device path"), and
  // separator coalescing collapses the rest. Result: a single `\`
  // current-drive root with the remainder as components.
  //
  // The proposal documents only EXACTLY-two-backslash UNC/device forms
  // (lines 204-214); it is SILENT on 3+ leading backslashes. Behavior pinned
  // here is observed-only.
  @Test
  func probeWindowsThreePlusBackslashes() {
    probe(#"\\\server\share"#, platform: .windows,
      anchor: #"\"#, components: ["server", "share"],
      printed: #"\server\share"#)
    probe(#"\\\\server"#, platform: .windows,
      anchor: #"\"#, components: ["server"],
      printed: #"\server"#)
    probe(#"\\\"#, platform: .windows,
      anchor: #"\"#, components: [],
      printed: #"\"#)
  }

  // MARK: - Probe 4: Windows degenerate device/sigil forms
  //
  // FINDING / GAP: a `\\.` or `\\?` with NO trailing backslash and NO device
  // name gets a backslash SYNTHESIZED by `_prenormalizeWindowsRoots`
  // (`expectBackslash` inserts one), yielding the empty-device anchors `\\.\`
  // / `\\?\`. These are classified absolute; `\\?` becomes verbatim-component.
  //
  // The proposal shows device/verbatim anchors only WITH a device name
  // (`\\.\pipe`, `\\?\C:\`, ...); it is SILENT on the empty-device forms.
  // (The trailing-backslash variants `\\.\` and `\\?\` already have rows in
  // PathTestCases.swift and are not re-asserted.)
  @Test
  func probeWindowsDegenerateDeviceSigil() {
    probe(#"\\."#, platform: .windows,
      anchor: #"\\.\"#, components: [],
      printed: #"\\.\"#)
    probe(#"\\?"#, platform: .windows,
      anchor: #"\\?\"#, components: [],
      printed: #"\\?\"#)

    // Extra observed properties for the same inputs (proposal SILENT).
    // Route through String-typed locals so the failable `init?(_:)` is
    // selected (a bare string literal would bind the non-failable
    // ExpressibleByStringLiteral `init`, which is not optional).
    withPlatform(.windows) {
      let dotInput: String = #"\\."#
      let dot = FilePath(dotInput)!
      expectTrue(dot.isAbsolute, #"\\. should be absolute (observed)"#)
      expectFalse(dot.anchor?._isVerbatimComponent ?? true,
        #"\\. is device-namespace, not verbatim (observed)"#)

      let qInput: String = #"\\?"#
      let q = FilePath(qInput)!
      expectTrue(q.isAbsolute, #"\\? should be absolute (observed)"#)
      expectTrue(q.anchor?._isVerbatimComponent ?? false,
        #"\\? becomes verbatim-component (observed)"#)
    }
  }

  // MARK: - Probe 5: _matches* prefix pre-filter near-misses
  //
  // CONFIRMS (no gap): `_matchesNofollow`/`_matchesResolve`/`_matchesVol` are
  // prefix PRE-FILTERS; the real validation (the required trailing `/` after
  // the keyword, the FSID/FILEID slashes) lives in `_parseNofollow`/
  // `_parseResolve`/`_parseVol`. A near-miss whose keyword is only a PREFIX of
  // the component (`/.nofollowing`, `/.resolved`, `/.volume`, `/.resolvex`)
  // therefore fails the parser and falls through to a plain `/` root with the
  // bytes as regular components.
  //
  // SPECIFIED by the proposal's general model (only the exact anchor forms are
  // recognized; everything else is an opaque component — proposal lines 91,
  // 103). Analogous rows already exist (`/.hidden/foo`, `/.Resolve/0/foo`);
  // these specific prefix-overlap near-misses are new.
  @Test
  func probeMatchesPrefixNearMisses() {
    probe("/.nofollowing/bar", platform: .darwin,
      anchor: "/", components: [".nofollowing", "bar"],
      printed: "/.nofollowing/bar")
    probe("/.resolved/x", platform: .darwin,
      anchor: "/", components: [".resolved", "x"],
      printed: "/.resolved/x")
    probe("/.volume/x", platform: .darwin,
      anchor: "/", components: [".volume", "x"],
      printed: "/.volume/x")
    probe("/.resolvex/1/y", platform: .darwin,
      anchor: "/", components: [".resolvex", "1", "y"],
      printed: "/.resolvex/1/y")
    // Keyword present but missing the structural slashes:
    // `.vol` with no FSID/FILEID, and FSID but no FILEID.
    probe("/.vol", platform: .darwin,
      anchor: "/", components: [".vol"],
      printed: "/.vol")
    probe("/.vol/1234", platform: .darwin,
      anchor: "/", components: [".vol", "1234"],
      printed: "/.vol/1234")
  }
}
